#!/usr/bin/env python3

import sys

from evolution.client.dealer_proxy import RemoteDealerProxy


def main():
    try:
        host, port = sys.argv[1], int(sys.argv[2])

        dealer_proxy = RemoteDealerProxy(host, port)
        dealer_proxy.request_join()
    except:
        raise


if __name__ == '__main__':
    main()
